title: Chad Breece
logo: /assets/img/profilepic.jpeg
description: My personal website, professional portfolio, and blog.
show_downloads: false
google_analytics: G-6GQH8T0FZH
theme: jekyll-theme-minimal
